logging:
  config: classpath:log4j2-local.xml
  level:
    web: DEBUG

idm-auth:
  enabled: true
  base-url: https://auth-dev.gmntc.com

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth-dev.gmntc.com